openapi: 3.0.0
info:
  version: 1.0.0
  title: Fullstack Vizsgaremek - Oltópont API
  description: API for the FullStack Vizsgaremek
servers:
  - url: http://localhost:3000
paths:
  /patient:
    get:
      description: Returns a list of patients
      responses:
        "200":
          description: List of patients returned successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Patient"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      description: Creates a new patient
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Patient"
      responses:
        "201":
          description: Patient has been created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Patient"
        "400":
          description: Invalid request when the post data is invalid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /patient/{_id}:
    get:
      description: Get a Patient
      parameters:
        - in: path
          name: _id
          required: true
          schema: 
            type: string
      responses:
        '200':
          description: Returns a Patient
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Patient'
        '404':
          description: Patient based on id doesn't exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    patch:
      description: Updates a Patient
      parameters:
        - in: path
          name: _id
          required: true
          schema: 
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Patient'
      responses:
        '200':
          description: Patient has been updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
        '400':
          description: Invalid request when the post data is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      description: Removes a Patient
      parameters:
        - in: path
          name: _id
          required: true
          schema: 
            type: string
      responses:
        '200':
          description: Patient has been deleted successfully
          content:
            application/json:
              schema:
                type: object
                example: {}
        '404':
          description: Patient based on id doesn't exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /person:
    get:
      description: Returns a list of persons
      responses:
        "200":
          description: List of persons returned successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Person"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      description: Creates a new person
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Person"
      responses:
        "201":
          description: Person has been created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Person"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /person/{person_id}:
    get:
      description: Returns the person with the given ID
      parameters:
        - name: person_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Person data returned successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Person"
        "404":
          description: Person with the give ID was not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    AdverseEvent:
      type: object
      required:
        - patient
        - date
        - description
      properties:
        patient:
          type: string
        date:
          type: string
        description:
          type: string
    Patient:
      type: object
      required:
        - name
        - appointment
        - personalId
        - dob
        - phone
        - email
        - vaccine
        - active
      properties:
        name:
          type: string
        appointment:
          type: string
        personalId:
          type: string
        dob:
          type: string
        phone:
          type: string
        email:
          type: string
        vaccine:
          type: string
        vaccinations:
          type: string
        active:
          type: boolean
    Place:
      type: object
      required:
        - hospital
        - address
        - building
      properties:
        hospital:
          type: string
        address:
          type: string
        building:
          type: string
    Vaccination:
      type: object
      required:
        - patient
        - vaccine
        - date
        - dose
        - injectionSite
        - injectionType
        - adverseEvent
        - eeszt
        - place
      properties:
        patient:
          type: string
        vaccine:
          type: string
        date:
          type: string
        dose:
          type: number
        injectionSite:
          type: string
        injectionType:
          type: string
        adverseEvent:
          type: string
        eeszt:
          type: boolean
        place:
          type: string
    Vaccine:
      type: object
      required:
        - manufacture
        - product
        - lot
        - doseInterval
      properties:
        manufacture:
          type: string
        product:
          type: string
        lot:
          type: string
        doseInterval:
          type: number
    Person:
      type: object
      required:
        - first_name
        - last_name
        - email
      properties:
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
    Error:
      type: object
      required:
        - message
        - has_error
      properties:
        message:
          type: string
        has_error:
          type: boolean
